#ifndef __H_CMDDEFINE_CLIENT_H__
#define __H_CMDDEFINE_CLIENT_H__

enum ClientRequest
{
	CLIENT_INVALID = 5000,
	ACCOUNT_CREATE,
	ACCOUNT_UPDATE,
	ACCOUNT_DEL,
	LOGIN_SERVER,
	LOGOUT_SERVER,
};

enum ServerRepley
{
	REPLY_INVALID = 6000,
	//ACCOUNT
	REPLY_RESULT_ACCOUNT_CAEATE,
	REPLY_RESULT_ACCOUNT_UPDATE,
	REPLY_RESULT_ACCOUNT_DEL,

	REPLY_RESULT_LOGIN_SERVER,
	REPLY_RESULT_LOGOUT_SERVER,
};
#endif