#ifndef __H_MANGER_CMD_DEFINE_H__
#define __H_MANGER_CMD_DEFINE_H__

enum RemoteServerType
{
	SERVER_TYPE_INVALD = 0,
	SERVER_TYPE_LOGIN,
	SERVER_TYPE_DATABASE,
	SERVER_TYPE_REDIS,
};

//
enum RedisServerRequest
{
	REDIS_REQUEST_INVALID = 30000,
	REDIS_REQUEST_LOGIN,
	REDIS_REQUEST_LOGOUT,
};
enum RedisServerReply
{
	REDIS_REPLY_INVALID = 31000,
	REDIS_REPLY_LOGIN,
	REDIS_REPLY_LOGOUT,
};

//
enum DatabaseServerRequest
{
	DATABASE_REQUEST_INVALID = 40000,
	DATABASE_REQUEST_LOGIN,
	DATABASE_REQUEST_LOGOUT,
	DATABASE_REQUEST_ACCOUNT_CREATE,
	DATABASE_REQUEST_ACCOUNT_UPDATE,
	DATABASE_REQUEST_ACCOUNT_DEL,
};
enum DatabaseServerReply
{
	DATABASE_REPLY_INVALID = 41000,
	DATABASE_REPLY_LOGIN,
	DATABASE_REPLY_LOGOUT,
	DATABASE_REPLY_ACCOUNT_CREATE,
	DATABASE_REPLY_ACCOUNT_UPDATE,
	DATABASE_REPLY_ACCOUNT_DEL,
};
#endif