#ifndef __H_MANGER_CMD_DEFINE_H__
#define __H_MANGER_CMD_DEFINE_H__

enum RemoteServerType
{
	SERVER_TYPE_INVALD = 0,
	SERVER_TYPE_LOGIN,
	SERVER_TYPE_DATABASE,
	SERVER_TYPE_REDIS,
};

enum LoginServerReply
{
	LOGIN_REPLY_INVALID = 20000,
	LOGIN_REPLY_LOGIN_SUCCESS,
	LOGIN_REPLY_LOGIN_FAIL,
};

enum RedisServerRequest
{
	REDIS_REQUEST_INVALID = 30000,
	REDIS_REQUEST_LOGIN,
	REDIS_REQUEST_LOGOUT,
};
enum RedisServerReply
{
	REDIS_REPLY_INVALID = 31000,
	REDIS_REPLY_LOGIN,
	REDIS_REPLY_LOGOUT,
};
#endif